dubbo:
    application:
        name: scheduler
    protocol:
        name: dubbo
        port: -1
    registry:
        id: zk-registry
        address: zookeeper://127.0.0.1:2181
    config-center:
        address: zookeeper://127.0.0.1:2181
    metadata-report:
        address: zookeeper://127.0.0.1:2181
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/scheduler?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimeZone=UTC%2B8
        username: root
        password: root
